CREATE TABLE customers (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(80) NOT NULL,
 email VARCHAR(254) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL
);
CREATE TABLE sessions (
 token_hash VARCHAR(64) PRIMARY KEY,
 customer_id BIGINT NOT NULL REFERENCES customers(id),
 expires_at TIMESTAMP NOT NULL
);
CREATE TABLE products (
 id BIGINT PRIMARY KEY, name VARCHAR(120) NOT NULL,
 description VARCHAR(1000) NOT NULL, category VARCHAR(50) NOT NULL,
 price NUMERIC(12,2) NOT NULL CHECK(price >= 0), icon VARCHAR(16) NOT NULL
);
CREATE TABLE cart_items (
 customer_id BIGINT NOT NULL REFERENCES customers(id),
 product_id BIGINT NOT NULL REFERENCES products(id),
 quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 99),
 PRIMARY KEY(customer_id, product_id)
);
CREATE TABLE orders (
 id VARCHAR(36) PRIMARY KEY,
 customer_id BIGINT NOT NULL REFERENCES customers(id),
 placed_at TIMESTAMP NOT NULL,
 total NUMERIC(12,2) NOT NULL,
 shipping_name VARCHAR(80) NOT NULL, address VARCHAR(200) NOT NULL,
 city VARCHAR(80) NOT NULL, postal_code VARCHAR(20) NOT NULL,
 status VARCHAR(30) NOT NULL
);
CREATE TABLE order_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id VARCHAR(36) NOT NULL REFERENCES orders(id),
 product_id BIGINT NOT NULL, name VARCHAR(120) NOT NULL,
 unit_price NUMERIC(12,2) NOT NULL, quantity INTEGER NOT NULL
);
CREATE INDEX orders_customer ON orders(customer_id);
