spring.application.name=shopsphere
server.port=8080
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/shopsphere;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.flyway.enabled=true
server.error.include-message=never
server.error.include-stacktrace=never
spring.jackson.deserialization.fail-on-unknown-properties=true
